# Generated by Django 6.0.3 on 2026-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FooterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        default="Kingdom Disciples Builders OTTO OUTREACH Ministry - Reaching the unreached and taking the light of the gospel to rural areas."
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2024 KDB OTTO OUTREACH Ministry. All Rights Reserved.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Content",
                "verbose_name_plural": "Footer Content",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="KDB OTTO OUTREACH Family", max_length=200
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="group/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Group Photo",
                "verbose_name_plural": "Group Photos",
            },
        ),
        migrations.CreateModel(
            name="HeroContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_title", models.CharField(default="KDB", max_length=200)),
                (
                    "subtitle",
                    models.CharField(
                        default="Kingdom Disciples Builders", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="We reach the unreached and take the light of the gospel to rural areas. Training ministers in the function of their ministerial assignment, bringing revival in church and among ministers."
                    ),
                ),
                (
                    "button1_text",
                    models.CharField(default="Explore Our Pillars", max_length=50),
                ),
                ("button1_link", models.CharField(default="#pillars", max_length=200)),
                ("button2_text", models.CharField(default="Contact Us", max_length=50)),
                ("button2_link", models.CharField(default="#contact", max_length=200)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                (
                    "background_video",
                    models.FileField(blank=True, null=True, upload_to="hero/"),
                ),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Section",
            },
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Rev Dr. Otto", max_length=200)),
                (
                    "title",
                    models.CharField(
                        default="Presiding Leader & Founder", max_length=200
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="leaders/"),
                ),
            ],
            options={
                "verbose_name": "Presiding Leader",
                "verbose_name_plural": "Presiding Leader",
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="bi-heart-fill", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Pillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acronym",
                    models.CharField(
                        help_text="e.g., LEP, EBO, DF, ISL", max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="bi-award-fill", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="bi-book", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="KDB Kingdom Disciples Builders", max_length=200
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(default="RC. 2614946", max_length=50),
                ),
                ("can_number", models.CharField(default="CAN 0294", max_length=50)),
                (
                    "mission_statement",
                    models.TextField(
                        default="Provoke revival in the church through effective evangelism, soul winning activities, leadership empowerment and ministerial training. Stand to build the disciples of the kingdom. Enhance integrity and effectiveness of Christian ministry."
                    ),
                ),
                (
                    "whatsapp_numbers",
                    models.JSONField(
                        default=list, help_text='Format: ["08052602905", "08060379587"]'
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="revottop@gmail.com", max_length=254),
                ),
                ("location", models.CharField(default="Nigeria", max_length=200)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("bank_name", models.CharField(default="UBA", max_length=100)),
                (
                    "account_number",
                    models.CharField(default="2191091914", max_length=20),
                ),
                (
                    "account_name",
                    models.CharField(default="KDB OTTO OUTREACH", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
