# Generated by Django 6.0.3 on 2026-03-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="announcements/"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload flyer PDF or image",
                        null=True,
                        upload_to="announcements/files/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("flyer", "Flyer/Poster"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload image, video, or flyer", upload_to="gallery/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Optional thumbnail for videos",
                        null=True,
                        upload_to="gallery/thumbnails/",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Upload background video",
                        null=True,
                        upload_to="hero/",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Fallback image for hero section",
                        null=True,
                        upload_to="hero/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Background",
                "verbose_name_plural": "Hero Backgrounds",
            },
        ),
    ]
