# Generated by Django 6.0.3 on 2026-03-16 07:58

import ministry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministry", "0002_announcement_galleryitem_herobackground"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GalleryImage",
        ),
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-date"],
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="galleryitem",
            options={
                "ordering": ["order", "-uploaded_at"],
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
            },
        ),
        migrations.AlterModelOptions(
            name="herobackground",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Hero Background",
                "verbose_name_plural": "Hero Backgrounds",
            },
        ),
        migrations.AddField(
            model_name="announcement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="herobackground",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="herobackground",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="pillar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="pillar",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Upload ministry logo (JPG, PNG)",
                null=True,
                upload_to="logos/",
                validators=[ministry.models.validate_image_file],
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload flyer PDF or image",
                null=True,
                upload_to="announcements/files/%Y/%m/",
                validators=[ministry.models.validate_pdf_file],
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="announcements/%Y/%m/",
                validators=[ministry.models.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="file",
            field=models.FileField(
                help_text="Upload image, video, or flyer",
                upload_to="gallery/%Y/%m/",
                validators=[ministry.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Optional thumbnail for videos",
                null=True,
                upload_to="gallery/thumbnails/%Y/%m/",
                validators=[ministry.models.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="group/",
                validators=[ministry.models.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="herobackground",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Fallback image for hero section",
                null=True,
                upload_to="hero/backgrounds/",
                validators=[ministry.models.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="herobackground",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload background video (MP4 recommended)",
                null=True,
                upload_to="hero/backgrounds/",
                validators=[ministry.models.validate_video_file],
            ),
        ),
        migrations.AlterField(
            model_name="herocontent",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="hero/",
                validators=[ministry.models.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="herocontent",
            name="background_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="hero/",
                validators=[ministry.models.validate_video_file],
            ),
        ),
        migrations.AlterField(
            model_name="leader",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="leaders/",
                validators=[ministry.models.validate_image_file],
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team/",
                validators=[ministry.models.validate_image_file],
            ),
        ),
    ]
